# Generated by Django 4.2.4 on 2023-08-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchquery_result_desc_searchquery_result_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(default='', max_length=200)),
                ('article_desc', models.TextField(default='', max_length=500)),
                ('article_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
