# Generated by Django 4.2.4 on 2023-08-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_articleposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleposts',
            name='article_image',
            field=models.ImageField(default='', upload_to='images/article_images'),
        ),
    ]
