# Generated by Django 4.2.4 on 2023-08-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_articleposts_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleposts',
            name='article_image',
            field=models.ImageField(default='', upload_to='static/images/article_images'),
        ),
    ]
