# Generated by Django 4.2.4 on 2023-08-21 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_alter_articleposts_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleposts',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Article Posts'},
        ),
        migrations.AddField(
            model_name='articleposts',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
