# Generated by Django 4.2.4 on 2023-08-21 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_articleposts_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleposts',
            name='article_tag',
            field=models.CharField(blank=True, default='', max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
