# Generated by Django 4.2.4 on 2023-08-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_alter_articleposts_article_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='articleposts',
            name='article_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
